[project]
name = "tiferet-lit-review"
version = "0.1.0"
description = "A literature review knowledge base app built with Tiferet."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tiferet>=2.0.0b3",
    "tiferet-h5>=0.1.0",
    "tiferet-kb>=1.0.0b2",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest_env",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]
